# Generated by Django 5.2.5 on 2025-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], default='Gender', max_length=10),
        ),
    ]
